// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/guigolab/rnaget-client/client/changelog"
	"github.com/guigolab/rnaget-client/client/expressions"
	"github.com/guigolab/rnaget-client/client/files"
	"github.com/guigolab/rnaget-client/client/get_versions"
	"github.com/guigolab/rnaget-client/client/projects"
	"github.com/guigolab/rnaget-client/client/studies"
)

// Default g a4 g h rnaget HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/rnaget"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new g a4 g h rnaget HTTP client.
func NewHTTPClient(formats strfmt.Registry) *GA4GHRnaget {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new g a4 g h rnaget HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *GA4GHRnaget {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new g a4 g h rnaget client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *GA4GHRnaget {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(GA4GHRnaget)
	cli.Transport = transport

	cli.Changelog = changelog.New(transport, formats)

	cli.Expressions = expressions.New(transport, formats)

	cli.Files = files.New(transport, formats)

	cli.GetVersions = get_versions.New(transport, formats)

	cli.Projects = projects.New(transport, formats)

	cli.Studies = studies.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// GA4GHRnaget is a client for g a4 g h rnaget
type GA4GHRnaget struct {
	Changelog *changelog.Client

	Expressions *expressions.Client

	Files *files.Client

	GetVersions *get_versions.Client

	Projects *projects.Client

	Studies *studies.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *GA4GHRnaget) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Changelog.SetTransport(transport)

	c.Expressions.SetTransport(transport)

	c.Files.SetTransport(transport)

	c.GetVersions.SetTransport(transport)

	c.Projects.SetTransport(transport)

	c.Studies.SetTransport(transport)

}
