// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new files API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for files API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetFile gets specific file

Returns download URL for file
*/
func (a *Client) GetFile(params *GetFileParams, authInfo runtime.ClientAuthInfoWriter) (*GetFileOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetFileParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getFile",
		Method:             "GET",
		PathPattern:        "/files/{fileID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetFileReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetFileOK), nil

}

/*
SearchFiles searches for files matching filters

Search for files matching filters.  Returns download URL or manifest of download URLs for matching file(s)
*/
func (a *Client) SearchFiles(params *SearchFilesParams, authInfo runtime.ClientAuthInfoWriter) (*SearchFilesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSearchFilesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "searchFiles",
		Method:             "GET",
		PathPattern:        "/files/search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &SearchFilesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*SearchFilesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
