location: crg
servers:
    crg:
        baseUrl: https://genome.crg.cat/rnaget
        token: abcdefuvwxyz
    caltech:
        baseUrl: https://felcat.caltech.edu/rnaget
    encode:
        baseUrl: https://rnaget.encodeproject.org
    gtex:
        baseUrl: http://gtexportal.org/rnaget