// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchProjectFiltersParams creates a new SearchProjectFiltersParams object
// with the default values initialized.
func NewSearchProjectFiltersParams() *SearchProjectFiltersParams {

	return &SearchProjectFiltersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchProjectFiltersParamsWithTimeout creates a new SearchProjectFiltersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchProjectFiltersParamsWithTimeout(timeout time.Duration) *SearchProjectFiltersParams {

	return &SearchProjectFiltersParams{

		timeout: timeout,
	}
}

// NewSearchProjectFiltersParamsWithContext creates a new SearchProjectFiltersParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchProjectFiltersParamsWithContext(ctx context.Context) *SearchProjectFiltersParams {

	return &SearchProjectFiltersParams{

		Context: ctx,
	}
}

// NewSearchProjectFiltersParamsWithHTTPClient creates a new SearchProjectFiltersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchProjectFiltersParamsWithHTTPClient(client *http.Client) *SearchProjectFiltersParams {

	return &SearchProjectFiltersParams{
		HTTPClient: client,
	}
}

/*SearchProjectFiltersParams contains all the parameters to send to the API endpoint
for the search project filters operation typically these are written to a http.Request
*/
type SearchProjectFiltersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search project filters params
func (o *SearchProjectFiltersParams) WithTimeout(timeout time.Duration) *SearchProjectFiltersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search project filters params
func (o *SearchProjectFiltersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search project filters params
func (o *SearchProjectFiltersParams) WithContext(ctx context.Context) *SearchProjectFiltersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search project filters params
func (o *SearchProjectFiltersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search project filters params
func (o *SearchProjectFiltersParams) WithHTTPClient(client *http.Client) *SearchProjectFiltersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search project filters params
func (o *SearchProjectFiltersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SearchProjectFiltersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
