// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/guigolab/rnaget-client/models"
)

// SearchProjectsReader is a Reader for the SearchProjects structure.
type SearchProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSearchProjectsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchProjectsOK creates a SearchProjectsOK with default headers values
func NewSearchProjectsOK() *SearchProjectsOK {
	return &SearchProjectsOK{}
}

/*SearchProjectsOK handles this case with default header values.

successful operation
*/
type SearchProjectsOK struct {
	Payload []*models.Project
}

func (o *SearchProjectsOK) Error() string {
	return fmt.Sprintf("[GET /projects/search][%d] searchProjectsOK  %+v", 200, o.Payload)
}

func (o *SearchProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchProjectsBadRequest creates a SearchProjectsBadRequest with default headers values
func NewSearchProjectsBadRequest() *SearchProjectsBadRequest {
	return &SearchProjectsBadRequest{}
}

/*SearchProjectsBadRequest handles this case with default header values.

Error
*/
type SearchProjectsBadRequest struct {
}

func (o *SearchProjectsBadRequest) Error() string {
	return fmt.Sprintf("[GET /projects/search][%d] searchProjectsBadRequest ", 400)
}

func (o *SearchProjectsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
