// Code generated by go-swagger; DO NOT EDIT.

package expressions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetExpressionByIDParams creates a new GetExpressionByIDParams object
// with the default values initialized.
func NewGetExpressionByIDParams() *GetExpressionByIDParams {
	var ()
	return &GetExpressionByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetExpressionByIDParamsWithTimeout creates a new GetExpressionByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetExpressionByIDParamsWithTimeout(timeout time.Duration) *GetExpressionByIDParams {
	var ()
	return &GetExpressionByIDParams{

		timeout: timeout,
	}
}

// NewGetExpressionByIDParamsWithContext creates a new GetExpressionByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetExpressionByIDParamsWithContext(ctx context.Context) *GetExpressionByIDParams {
	var ()
	return &GetExpressionByIDParams{

		Context: ctx,
	}
}

// NewGetExpressionByIDParamsWithHTTPClient creates a new GetExpressionByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetExpressionByIDParamsWithHTTPClient(client *http.Client) *GetExpressionByIDParams {
	var ()
	return &GetExpressionByIDParams{
		HTTPClient: client,
	}
}

/*GetExpressionByIDParams contains all the parameters to send to the API endpoint
for the get expression by Id operation typically these are written to a http.Request
*/
type GetExpressionByIDParams struct {

	/*ExpressionID
	  ID of expression to return

	*/
	ExpressionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get expression by Id params
func (o *GetExpressionByIDParams) WithTimeout(timeout time.Duration) *GetExpressionByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get expression by Id params
func (o *GetExpressionByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get expression by Id params
func (o *GetExpressionByIDParams) WithContext(ctx context.Context) *GetExpressionByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get expression by Id params
func (o *GetExpressionByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get expression by Id params
func (o *GetExpressionByIDParams) WithHTTPClient(client *http.Client) *GetExpressionByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get expression by Id params
func (o *GetExpressionByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExpressionID adds the expressionID to the get expression by Id params
func (o *GetExpressionByIDParams) WithExpressionID(expressionID string) *GetExpressionByIDParams {
	o.SetExpressionID(expressionID)
	return o
}

// SetExpressionID adds the expressionId to the get expression by Id params
func (o *GetExpressionByIDParams) SetExpressionID(expressionID string) {
	o.ExpressionID = expressionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetExpressionByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param expressionId
	if err := r.SetPathParam("expressionId", o.ExpressionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
