// Code generated by go-swagger; DO NOT EDIT.

package expressions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/guigolab/rnaget-client/models"
)

// SearchExpressionsReader is a Reader for the SearchExpressions structure.
type SearchExpressionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchExpressionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchExpressionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSearchExpressionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchExpressionsOK creates a SearchExpressionsOK with default headers values
func NewSearchExpressionsOK() *SearchExpressionsOK {
	return &SearchExpressionsOK{}
}

/*SearchExpressionsOK handles this case with default header values.

Successful operation
*/
type SearchExpressionsOK struct {
	Payload []*models.File
}

func (o *SearchExpressionsOK) Error() string {
	return fmt.Sprintf("[GET /expressions/search][%d] searchExpressionsOK  %+v", 200, o.Payload)
}

func (o *SearchExpressionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchExpressionsBadRequest creates a SearchExpressionsBadRequest with default headers values
func NewSearchExpressionsBadRequest() *SearchExpressionsBadRequest {
	return &SearchExpressionsBadRequest{}
}

/*SearchExpressionsBadRequest handles this case with default header values.

Error
*/
type SearchExpressionsBadRequest struct {
}

func (o *SearchExpressionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /expressions/search][%d] searchExpressionsBadRequest ", 400)
}

func (o *SearchExpressionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
