// Code generated by go-swagger; DO NOT EDIT.

package expressions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchExpressionFiltersParams creates a new SearchExpressionFiltersParams object
// with the default values initialized.
func NewSearchExpressionFiltersParams() *SearchExpressionFiltersParams {
	var ()
	return &SearchExpressionFiltersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchExpressionFiltersParamsWithTimeout creates a new SearchExpressionFiltersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchExpressionFiltersParamsWithTimeout(timeout time.Duration) *SearchExpressionFiltersParams {
	var ()
	return &SearchExpressionFiltersParams{

		timeout: timeout,
	}
}

// NewSearchExpressionFiltersParamsWithContext creates a new SearchExpressionFiltersParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchExpressionFiltersParamsWithContext(ctx context.Context) *SearchExpressionFiltersParams {
	var ()
	return &SearchExpressionFiltersParams{

		Context: ctx,
	}
}

// NewSearchExpressionFiltersParamsWithHTTPClient creates a new SearchExpressionFiltersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchExpressionFiltersParamsWithHTTPClient(client *http.Client) *SearchExpressionFiltersParams {
	var ()
	return &SearchExpressionFiltersParams{
		HTTPClient: client,
	}
}

/*SearchExpressionFiltersParams contains all the parameters to send to the API endpoint
for the search expression filters operation typically these are written to a http.Request
*/
type SearchExpressionFiltersParams struct {

	/*Type
	  one of `feature` or `sample` reflecting which axis to request filters for.  If blank, both will be returned

	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search expression filters params
func (o *SearchExpressionFiltersParams) WithTimeout(timeout time.Duration) *SearchExpressionFiltersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search expression filters params
func (o *SearchExpressionFiltersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search expression filters params
func (o *SearchExpressionFiltersParams) WithContext(ctx context.Context) *SearchExpressionFiltersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search expression filters params
func (o *SearchExpressionFiltersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search expression filters params
func (o *SearchExpressionFiltersParams) WithHTTPClient(client *http.Client) *SearchExpressionFiltersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search expression filters params
func (o *SearchExpressionFiltersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithType adds the typeVar to the search expression filters params
func (o *SearchExpressionFiltersParams) WithType(typeVar *string) *SearchExpressionFiltersParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the search expression filters params
func (o *SearchExpressionFiltersParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *SearchExpressionFiltersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
