// Code generated by go-swagger; DO NOT EDIT.

package changelog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new changelog API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for changelog API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetChangeLog gets change log for a specific release version

Returns changes associated with specified database release version
*/
func (a *Client) GetChangeLog(params *GetChangeLogParams, authInfo runtime.ClientAuthInfoWriter) (*GetChangeLogOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetChangeLogParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getChangeLog",
		Method:             "GET",
		PathPattern:        "/changelog/{version}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetChangeLogReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetChangeLogOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
