// Code generated by go-swagger; DO NOT EDIT.

package changelog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChangeLogParams creates a new GetChangeLogParams object
// with the default values initialized.
func NewGetChangeLogParams() *GetChangeLogParams {
	var ()
	return &GetChangeLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChangeLogParamsWithTimeout creates a new GetChangeLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChangeLogParamsWithTimeout(timeout time.Duration) *GetChangeLogParams {
	var ()
	return &GetChangeLogParams{

		timeout: timeout,
	}
}

// NewGetChangeLogParamsWithContext creates a new GetChangeLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChangeLogParamsWithContext(ctx context.Context) *GetChangeLogParams {
	var ()
	return &GetChangeLogParams{

		Context: ctx,
	}
}

// NewGetChangeLogParamsWithHTTPClient creates a new GetChangeLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChangeLogParamsWithHTTPClient(client *http.Client) *GetChangeLogParams {
	var ()
	return &GetChangeLogParams{
		HTTPClient: client,
	}
}

/*GetChangeLogParams contains all the parameters to send to the API endpoint
for the get change log operation typically these are written to a http.Request
*/
type GetChangeLogParams struct {

	/*Version
	  release version

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get change log params
func (o *GetChangeLogParams) WithTimeout(timeout time.Duration) *GetChangeLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get change log params
func (o *GetChangeLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get change log params
func (o *GetChangeLogParams) WithContext(ctx context.Context) *GetChangeLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get change log params
func (o *GetChangeLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get change log params
func (o *GetChangeLogParams) WithHTTPClient(client *http.Client) *GetChangeLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get change log params
func (o *GetChangeLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVersion adds the version to the get change log params
func (o *GetChangeLogParams) WithVersion(version string) *GetChangeLogParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get change log params
func (o *GetChangeLogParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetChangeLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
