// Code generated by go-swagger; DO NOT EDIT.

package get_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetGetVersionsReader is a Reader for the GetGetVersions structure.
type GetGetVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGetVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetGetVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetGetVersionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGetVersionsOK creates a GetGetVersionsOK with default headers values
func NewGetGetVersionsOK() *GetGetVersionsOK {
	return &GetGetVersionsOK{}
}

/*GetGetVersionsOK handles this case with default header values.

Successful operation
*/
type GetGetVersionsOK struct {
	Payload map[string]string
}

func (o *GetGetVersionsOK) Error() string {
	return fmt.Sprintf("[GET /getVersions][%d] getGetVersionsOK  %+v", 200, o.Payload)
}

func (o *GetGetVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetGetVersionsBadRequest creates a GetGetVersionsBadRequest with default headers values
func NewGetGetVersionsBadRequest() *GetGetVersionsBadRequest {
	return &GetGetVersionsBadRequest{}
}

/*GetGetVersionsBadRequest handles this case with default header values.

Invalid tag value
*/
type GetGetVersionsBadRequest struct {
}

func (o *GetGetVersionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /getVersions][%d] getGetVersionsBadRequest ", 400)
}

func (o *GetGetVersionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
