// Code generated by go-swagger; DO NOT EDIT.

package get_versions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetGetVersionsParams creates a new GetGetVersionsParams object
// with the default values initialized.
func NewGetGetVersionsParams() *GetGetVersionsParams {

	return &GetGetVersionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGetVersionsParamsWithTimeout creates a new GetGetVersionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGetVersionsParamsWithTimeout(timeout time.Duration) *GetGetVersionsParams {

	return &GetGetVersionsParams{

		timeout: timeout,
	}
}

// NewGetGetVersionsParamsWithContext creates a new GetGetVersionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGetVersionsParamsWithContext(ctx context.Context) *GetGetVersionsParams {

	return &GetGetVersionsParams{

		Context: ctx,
	}
}

// NewGetGetVersionsParamsWithHTTPClient creates a new GetGetVersionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGetVersionsParamsWithHTTPClient(client *http.Client) *GetGetVersionsParams {

	return &GetGetVersionsParams{
		HTTPClient: client,
	}
}

/*GetGetVersionsParams contains all the parameters to send to the API endpoint
for the get get versions operation typically these are written to a http.Request
*/
type GetGetVersionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get get versions params
func (o *GetGetVersionsParams) WithTimeout(timeout time.Duration) *GetGetVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get get versions params
func (o *GetGetVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get get versions params
func (o *GetGetVersionsParams) WithContext(ctx context.Context) *GetGetVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get get versions params
func (o *GetGetVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get get versions params
func (o *GetGetVersionsParams) WithHTTPClient(client *http.Client) *GetGetVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get get versions params
func (o *GetGetVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetGetVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
