// Code generated by go-swagger; DO NOT EDIT.

package studies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/guigolab/rnaget-client/models"
)

// GetStudyByIDReader is a Reader for the GetStudyByID structure.
type GetStudyByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStudyByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetStudyByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetStudyByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetStudyByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStudyByIDOK creates a GetStudyByIDOK with default headers values
func NewGetStudyByIDOK() *GetStudyByIDOK {
	return &GetStudyByIDOK{}
}

/*GetStudyByIDOK handles this case with default header values.

successful operation
*/
type GetStudyByIDOK struct {
	Payload *models.Study
}

func (o *GetStudyByIDOK) Error() string {
	return fmt.Sprintf("[GET /studies/{studyId}][%d] getStudyByIdOK  %+v", 200, o.Payload)
}

func (o *GetStudyByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Study)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStudyByIDBadRequest creates a GetStudyByIDBadRequest with default headers values
func NewGetStudyByIDBadRequest() *GetStudyByIDBadRequest {
	return &GetStudyByIDBadRequest{}
}

/*GetStudyByIDBadRequest handles this case with default header values.

Invalid ID supplied
*/
type GetStudyByIDBadRequest struct {
}

func (o *GetStudyByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /studies/{studyId}][%d] getStudyByIdBadRequest ", 400)
}

func (o *GetStudyByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetStudyByIDNotFound creates a GetStudyByIDNotFound with default headers values
func NewGetStudyByIDNotFound() *GetStudyByIDNotFound {
	return &GetStudyByIDNotFound{}
}

/*GetStudyByIDNotFound handles this case with default header values.

Study not found
*/
type GetStudyByIDNotFound struct {
}

func (o *GetStudyByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /studies/{studyId}][%d] getStudyByIdNotFound ", 404)
}

func (o *GetStudyByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
