// Code generated by go-swagger; DO NOT EDIT.

package studies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/guigolab/rnaget-client/models"
)

// SearchStudiesReader is a Reader for the SearchStudies structure.
type SearchStudiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchStudiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchStudiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSearchStudiesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchStudiesOK creates a SearchStudiesOK with default headers values
func NewSearchStudiesOK() *SearchStudiesOK {
	return &SearchStudiesOK{}
}

/*SearchStudiesOK handles this case with default header values.

successful operation
*/
type SearchStudiesOK struct {
	Payload []*models.Study
}

func (o *SearchStudiesOK) Error() string {
	return fmt.Sprintf("[GET /studies/search][%d] searchStudiesOK  %+v", 200, o.Payload)
}

func (o *SearchStudiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchStudiesBadRequest creates a SearchStudiesBadRequest with default headers values
func NewSearchStudiesBadRequest() *SearchStudiesBadRequest {
	return &SearchStudiesBadRequest{}
}

/*SearchStudiesBadRequest handles this case with default header values.

Error
*/
type SearchStudiesBadRequest struct {
}

func (o *SearchStudiesBadRequest) Error() string {
	return fmt.Sprintf("[GET /studies/search][%d] searchStudiesBadRequest ", 400)
}

func (o *SearchStudiesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
