// Code generated by go-swagger; DO NOT EDIT.

package studies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSearchStudyFiltersParams creates a new SearchStudyFiltersParams object
// with the default values initialized.
func NewSearchStudyFiltersParams() *SearchStudyFiltersParams {

	return &SearchStudyFiltersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchStudyFiltersParamsWithTimeout creates a new SearchStudyFiltersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchStudyFiltersParamsWithTimeout(timeout time.Duration) *SearchStudyFiltersParams {

	return &SearchStudyFiltersParams{

		timeout: timeout,
	}
}

// NewSearchStudyFiltersParamsWithContext creates a new SearchStudyFiltersParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchStudyFiltersParamsWithContext(ctx context.Context) *SearchStudyFiltersParams {

	return &SearchStudyFiltersParams{

		Context: ctx,
	}
}

// NewSearchStudyFiltersParamsWithHTTPClient creates a new SearchStudyFiltersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchStudyFiltersParamsWithHTTPClient(client *http.Client) *SearchStudyFiltersParams {

	return &SearchStudyFiltersParams{
		HTTPClient: client,
	}
}

/*SearchStudyFiltersParams contains all the parameters to send to the API endpoint
for the search study filters operation typically these are written to a http.Request
*/
type SearchStudyFiltersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search study filters params
func (o *SearchStudyFiltersParams) WithTimeout(timeout time.Duration) *SearchStudyFiltersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search study filters params
func (o *SearchStudyFiltersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search study filters params
func (o *SearchStudyFiltersParams) WithContext(ctx context.Context) *SearchStudyFiltersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search study filters params
func (o *SearchStudyFiltersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search study filters params
func (o *SearchStudyFiltersParams) WithHTTPClient(client *http.Client) *SearchStudyFiltersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search study filters params
func (o *SearchStudyFiltersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SearchStudyFiltersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
