// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ExpressionSearchFilter parameter name to use for filter when searching
// swagger:model expressionSearchFilter
type ExpressionSearchFilter struct {

	// filter type
	FilterType string `json:"filterType,omitempty"`

	// filters
	Filters []string `json:"filters"`
}

// Validate validates this expression search filter
func (m *ExpressionSearchFilter) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExpressionSearchFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExpressionSearchFilter) UnmarshalBinary(b []byte) error {
	var res ExpressionSearchFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
